services:
  postgres:
    image: postgres:17-alpine
    container_name: conference-booking-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: conference-booking-api
    restart: unless-stopped

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: >-
        Host=postgres;
        Port=5432;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}

      Booking__TimeZone: Europe/Kyiv

      Database__ApplyMigrationsOnStartup: "true"
      
      Jwt__Key: ${JWT_KEY}
      
      Admin__SeedOnStartup: "true"
      Admin__Email: ${ADMIN_EMAIL}
      Admin__Password: ${ADMIN_PASSWORD}
    ports:
      - "5034:8080"

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: